In [4]:
import boto3
import pandas as pd
from io import StringIO

In [5]:
s3 = boto3.resource('s3')
bucket = s3.Bucket('xetra-1234')

bucket_obj = bucket.objects.filter(Prefix='2022-01-28/')

In [6]:
objects = [obj for obj in bucket_obj]

objects

[s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR23.csv')]

csv_obj = bucket.Object(key = '2022-01-28/2022-01-28_BINS_XETR16.csv').get().get('Body').read().decode('utf-8')
csv_obj

In [12]:
## Converting to Dataframe 
data = StringIO(csv_obj)

df= pd.read_csv(data, delimiter= ',')
df.head(50)

,ISIN,Mnemonic,SecurityDesc,SecurityType,Currency,SecurityID,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume,NumberOfTrades
0,DE000ETFL011,EL4A,DK DAX,ETF,EUR,2504258,2022-01-28,16:00,137.240,137.240,137.240,137.240,13,1
1,DE000ETFL060,EL4F,DK DAX (AUSSCHUETTEND),ETF,EUR,2504259,2022-01-28,16:00,64.630,64.630,64.630,64.630,49,1
2,DE0002635273,EXSB,ISHARES DIVDAX UCITS ETF,ETF,EUR,2504264,2022-01-28,16:00,20.510,20.510,20.510,20.510,100,1
3,DE0005933931,EXS1,ISHS CORE DAX UC.ETF EOA,ETF,EUR,2504265,2022-01-28,16:00,129.540,129.540,129.500,129.500,220,2
4,LU0252634307,LYY8,MUL-LYX.DLY.LEVDAX U.E. A,ETF,EUR,2504268,2022-01-28,16:00,130.520,130.520,130.480,130.480,158,2
5,LU0274211480,DBXD,XTR.DAX 1C,ETF,EUR,2504269,2022-01-28,16:00,146.220,146.220,146.220,146.220,12,1
6,LU0292106241,DXSN,XTR.SHORTDAX DAILY SW. 1C,ETF,EUR,2504270,2022-01-28,16:00,13.962,13.962,13.962,13.962,36,1
7,LU0378438732,C001,LYXOR CORE DAX U. ETF I,ETF,EUR,2504271,2022-01-28,16:00,129.440,129.440,129.440,129.440,18,2
8,LU0411075020,DBPD,XTR.SHORTDAX X2 DA.SW. 1C,ETF,EUR,2504272,2022-01-28,16:00,1.420,1.420,1.420,1.420,136222,15
9,DE000A0DNAY5,ACX,BET-AT-HOME.COM AG O.N.,Common stock,EUR,2504288,2022-01-28,16:00,15.180,15.220,15.180,15.200,252,8
10,DE000A0D6554,NDX1,NORDEX SE O.N.,Common stock,EUR,2504290,2022-01-28,16:00,13.270,13.270,13.260,13.270,6446,13
11,DE000A0D8Q07,EXSI,ISHARES EURO STOXX U.ETF,ETF,EUR,2504292,2022-01-28,16:00,45.355,45.355,45.355,45.355,47,1
12,DE000A0D9PT0,MTX,MTU AERO ENGINES NA O.N.,Common stock,EUR,2504297,2022-01-28,16:00,185.200,185.200,185.000,185.000,83,5
13,DE000A0F5UG3,EXXV,IS.DJ EUROZ.SUST.SC.U.ETF,ETF,EUR,2504304,2022-01-28,16:00,15.090,15.090,15.090,15.090,40,1
14,DE000A0F5UH1,ISPA,IS.S.GL.SE.D.100 U.ETF A.,ETF,EUR,2504305,2022-01-28,16:00,30.225,30.225,30.225,30.225,150,1
15,DE000A0F5UJ7,EXV1,IS.S.EU.600 BANK.U.ETF A.,ETF,EUR,2504306,2022-01-28,16:00,15.322,15.322,15.322,15.322,1007,1
16,DE000A0F5UK5,EXV6,IS.S.E.600 BA.RE.U.ETF A.,ETF,EUR,2504307,2022-01-28,16:00,62.700,62.700,62.680,62.680,803,2
17,DE000A0H0728,EXXY,ISHS DIV.COMM.SWAP UC.ETF,ETF,EUR,2504315,2022-01-28,16:00,24.330,24.330,24.330,24.330,154,1
18,DE000A0H08J9,EXH4,IS.S.E.600 I.G+S.U.ETF A.,ETF,EUR,2504327,2022-01-28,16:00,71.370,71.370,71.370,71.370,438,1
19,DE000A0H08L5,EXH6,IS.S.E.600 MEDIA U.ETF A.,ETF,EUR,2504329,2022-01-28,16:00,29.710,29.710,29.710,29.710,1,1
20,DE000A0H08M3,EXH1,IS.S.E.600 OIL+G.U.ETF A.,ETF,EUR,2504330,2022-01-28,16:00,30.595,30.595,30.595,30.595,81,1
21,DE000A0H08Q4,EXV3,ISH.S.EU.600 TEC.U.ETF A.,ETF,EUR,2504333,2022-01-28,16:00,65.600,65.600,65.590,65.590,20,2
22,DE000A0H08R2,EXV2,ISH.S.EU.600 TEL.U.ETF A.,ETF,EUR,2504334,2022-01-28,16:00,21.660,21.660,21.660,21.660,12,1
23,DE000A0H08S0,EXV9,ISH.S.EU.600 T+L U.ETF A.,ETF,EUR,2504335,2022-01-28,16:00,20.950,20.950,20.950,20.950,193,1
24,DE000A0JC8S7,D6H,DATAGROUP SE INH. O.N.,Common stock,EUR,2504338,2022-01-28,16:00,82.800,82.800,82.800,82.800,25,3
25,DE000A0JK2A8,AR4,AURELIUS EQ.OPP. O.N.,Common stock,EUR,2504340,2022-01-28,16:00,27.520,27.540,27.520,27.540,57,2
26,DE000A0JL9W6,VBK,VERBIO VER.BIOENERGIE ON,Common stock,EUR,2504343,2022-01-28,16:00,51.750,51.850,51.700,51.700,518,7
27,DE000A0Q4R02,EXH9,ISH.S.EU.600 UTI.U.ETF A.,ETF,EUR,2504392,2022-01-28,16:00,39.625,39.625,39.625,39.625,54,1
28,DE000A0Q4R28,EXV5,ISH.S.EU.600 A+P U.ETF A.,ETF,EUR,2504393,2022-01-28,16:00,60.660,60.670,60.660,60.670,112,3
29,DE000A0Q4R36,EXV4,IS.S.E.600 HEA.C.U.ETF A.,ETF,EUR,2504394,2022-01-28,16:00,99.910,99.910,99.910,99.910,6,1
30,DE000A0STSQ8,M12,M1 KLINIKEN AG O.N.,Common stock,EUR,2504400,2022-01-28,16:00,7.260,7.260,7.180,7.180,6624,2
31,DE000A0WMPJ6,AIXA,AIXTRON SE NA O.N.,Common stock,EUR,2504428,2022-01-28,16:00,17.560,17.570,17.550,17.570,4019,15
32,DE000A0Z2ZZ5,FNTN,FREENET AG NA O.N.,Common stock,EUR,2504438,2022-01-28,16:00,24.180,24.180,24.180,24.180,393,1
33,DE000A0Z23Q5,ADN1,ADESSO SE INH O.N.,Common stock,EUR,2504440,2022-01-28,16:00,173.000,173.400,173.000,173.400,74,6
34,DE000A1DAHH0,BNR,BRENNTAG SE NA O.N.,Common stock,EUR,2504453,2022-01-28,16:00,75.280,75.280,75.240,75.240,638,5
35,DE000A1EWWW0,ADS,ADIDAS AG NA O.N.,Common stock,EUR,2504471,2022-01-28,16:00,236.050,236.250,236.050,236.150,2018,31
36,DE000A1H8BV3,NOEJ,NORMA GROUP SE NA O.N.,Common stock,EUR,2504474,2022-01-28,16:00,32.300,32.300,32.300,32.300,24,2
37,DE000A1J5RX9,O2D,TELEFONICA DTLD HLDG NA,Common stock,EUR,2504492,2022-01-28,16:00,2.569,2.570,2.569,2.569,6701,5
38,DE000A1ML7J1,VNA,VONOVIA SE NA O.N.,Common stock,EUR,2504501,2022-01-28,16:00,50.540,50.540,50.540,50.540,1151,6
39,DE000A1PHFF7,BOSS,HUGO BOSS AG NA O.N.,Common stock,EUR,2504512,2022-01-28,16:00,54.280,54.320,54.280,54.300,612,6
40,DE000A11QW68,HRPK,7C SOLARPARKEN AG O.N.,Common stock,EUR,2504548,2022-01-28,16:00,4.075,4.080,4.075,4.075,1688,6
41,DE000A12DM80,G24,SCOUT24 SE NA O.N.,Common stock,EUR,2504556,2022-01-28,16:00,51.900,51.900,51.900,51.900,336,3
42,DE000BASF111,BAS,BASF SE NA O.N.,Common stock,EUR,2504663,2022-01-28,16:00,68.250,68.250,68.190,68.210,1387,15
43,DE000BAY0017,BAYN,BAYER AG NA O.N.,Common stock,EUR,2504664,2022-01-28,16:00,52.700,52.710,52.670,52.670,4016,18
44,DE000CBK1001,CBK,COMMERZBANK AG,Common stock,EUR,2504665,2022-01-28,16:00,7.584,7.584,7.571,7.576,9806,14
45,DE000ENAG999,EOAN,E.ON SE NA O.N.,Common stock,EUR,2504666,2022-01-28,16:00,12.256,12.256,12.248,12.252,31052,24
46,DE000ETFL037,EL4C,DK STOXX EUR.STR.GROW.20,ETF,EUR,2504683,2022-01-28,16:00,54.010,54.010,54.010,54.010,36,1
47,DE000ETFL052,EL4E,DK STOXX EUR.STR.STY.C.40,ETF,EUR,2504685,2022-01-28,16:00,37.900,37.900,37.900,37.900,11,1
48,DE000ETFL086,EL4H,DK MSCI EUROPE LC,ETF,EUR,2504686,2022-01-28,16:00,109.360,109.360,109.360,109.360,5,1
49,DE000ETFL284,EL42,DK MSCI EUROPE,ETF,EUR,2504704,2022-01-28,16:00,15.590,15.590,15.590,15.590,45,1

## Read Multiple Files

In [14]:
bucket_obj1 = bucket.objects.filter(Prefix='2022-01-28/')
bucket_obj2 = bucket.objects.filter(Prefix='2022-01-31/')
objects = [obj for obj in bucket_obj1] + [obj for obj in bucket_obj2]

objects

[s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-28/2022-01-28_BINS_XETR23.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-01-31/2022-01-31_BINS_XETR23.csv')]

In [15]:
csv_obj_init = bucket.Object(key = objects[0].key).get().get('Body').read().decode('utf-8')
data = StringIO(csv_obj_init)
df_init = pd.read_csv(data, delimiter= ',')

df_init.columns

Index(['ISIN', 'Mnemonic', 'SecurityDesc', 'SecurityType', 'Currency',
       'SecurityID', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice',
       'EndPrice', 'TradedVolume', 'NumberOfTrades'],
      dtype='object')

In [19]:
df_all = pd.DataFrame(columns=df_init.columns)

# Use pd.concat to combine DataFrames
all_dfs = []  # Create a list to store DataFrames

for obj in objects:
    csv_obj = bucket.Object(key=obj.key).get().get('Body').read().decode('utf-8')
    data = StringIO(csv_obj)
    df = pd.read_csv(data, delimiter=',')
    all_dfs.append(df)  # Append the current DataFrame to the list

df_all = pd.concat(all_dfs, ignore_index=True)

/var/folders/ks/wd71lv4n19x644x32rwqs4q40000gn/T/ipykernel_62678/1222606547.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all = pd.concat(all_dfs, ignore_index=True)

In [20]:
df_all

,ISIN,Mnemonic,SecurityDesc,SecurityType,Currency,SecurityID,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume,NumberOfTrades
0,AT0000A0E9W5,SANT,S+T AG O.N.,Common stock,EUR,2504159,2022-01-28,08:00,16.39,16.44,16.39,16.44,3249,4
1,DE000A0DJ6J9,S92,SMA SOLAR TECHNOL.AG,Common stock,EUR,2504287,2022-01-28,08:00,31.30,31.30,30.98,31.02,13383,24
2,DE000A0D6554,NDX1,NORDEX SE O.N.,Common stock,EUR,2504290,2022-01-28,08:00,13.26,13.32,13.26,13.30,12572,29
3,DE000A0D9PT0,MTX,MTU AERO ENGINES NA O.N.,Common stock,EUR,2504297,2022-01-28,08:00,190.45,190.45,189.55,190.05,1413,26
4,DE000A0HN5C6,DWNI,DEUTSCHE WOHNEN SE INH,Common stock,EUR,2504314,2022-01-28,08:00,35.65,35.74,35.65,35.74,414,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246956,DE000A2GS401,SOW,SOFTWARE AG NA O.N.,Common stock,EUR,2696229,2022-01-31,16:44,34.08,34.08,34.08,34.08,30,2
246957,IE00BMQ8YQ50,SOFT,HANETF-PESWESGS DLA,ETF,EUR,6667428,2022-01-31,16:51,5.35,5.35,5.35,5.35,17000,2
246958,US8793691069,TBH,TELEFLEX INC. DL 1,Common stock,EUR,6001412,2022-01-31,20:30,266.00,266.00,266.00,266.00,0,1
246959,LU2380748603,SPV2,468 SPAC II SE EO 1,Common stock,EUR,7285960,2022-01-31,20:30,10.10,10.10,10.10,10.10,0,1
246960,DE000A3MQDG4,BIO2,BIOTEST AG ST ANGEDIENT.,Common stock,EUR,7335008,2022-01-31,20:30,42.00,42.00,42.00,42.00,0,1

In [24]:
columns = ['ISIN', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice',
       'EndPrice', 'TradedVolume']

df_all = df_all.loc[:, columns]
df_all

,ISIN,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume
0,AT0000A0E9W5,2022-01-28,08:00,16.39,16.44,16.39,16.44,3249
1,DE000A0DJ6J9,2022-01-28,08:00,31.30,31.30,30.98,31.02,13383
2,DE000A0D6554,2022-01-28,08:00,13.26,13.32,13.26,13.30,12572
3,DE000A0D9PT0,2022-01-28,08:00,190.45,190.45,189.55,190.05,1413
4,DE000A0HN5C6,2022-01-28,08:00,35.65,35.74,35.65,35.74,414
...,...,...,...,...,...,...,...,...
246956,DE000A2GS401,2022-01-31,16:44,34.08,34.08,34.08,34.08,30
246957,IE00BMQ8YQ50,2022-01-31,16:51,5.35,5.35,5.35,5.35,17000
246958,US8793691069,2022-01-31,20:30,266.00,266.00,266.00,266.00,0
246959,LU2380748603,2022-01-31,20:30,10.10,10.10,10.10,10.10,0
246960,DE000A3MQDG4,2022-01-31,20:30,42.00,42.00,42.00,42.00,0

In [25]:
## Filtering- Dropping cases where there is no data

df_all.dropna(inplace=True)

In [26]:
df_all.shape

(246961, 8)